In [40]:
# import data

from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [41]:
train_images.shape, len(train_labels)

((60000, 28, 28), 60000)

In [42]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [43]:
test_images.shape, len(test_labels)

((10000, 28, 28), 10000)

In [44]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], shape=(10000,), dtype=uint8)

# Build the network

In [45]:
import keras
from keras import layers

model = keras.Sequential(
    [
        layers.Dense(512, activation="relu"),
        layers.Dense(10, activation="softmax"),
    ]
)

In [46]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

# Preprocess the data

In [47]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [48]:
history = model.fit(
          train_images, 
          train_labels, 
          epochs=5,
          verbose=1,
          batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9261 - loss: 0.2659
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9686 - loss: 0.1081
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9795 - loss: 0.0694
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9852 - loss: 0.0496
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9893 - loss: 0.0375


In [ ]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0].argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([8.4277850e-08, 3.1872047e-09, 2.5599991e-06, 3.7181628e-05,
       2.2539959e-10, 1.0846040e-07, 1.3984344e-12, 9.9995780e-01,
       7.7388329e-08, 2.1350481e-06], dtype=float32)

In [50]:
predictions[0].argmax()

np.int64(7)

In [51]:
test_labels[0]

np.uint8(7)

In [52]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.9810 - loss: 0.0623
test_acc: 0.9810000061988831
